export const ActionTypes = {
  UPDATE_EXPENSE_AMOUNT: 'UPDATE_EXPENSE_AMOUNT',
  UPDATE_EXPENSE_DESCRIPTION: 'UPDATE_EXPENSE_DESCRIPTION',
  SUBMIT_EXPENSE: 'SUBMIT_EXPENSE',
  ADD_EXPENSE_TO_LIST: 'ADD_EXPENSE_TO_LIST',
}
