export const ActionTypes = {
  UPDATE_EXPENSE_AMOUNT: 'UPDATE_EXPENSE_AMOUNT',
  UPDATE_EXPENSE_DESCRIPTION: 'UPDATE_EXPENSE_DESCRIPTION',
  ADD_EXPENSE_TO_LIST: 'ADD_EXPENSE_TO_LIST',
  UPDATE_BALANCE: 'UPDATE_BALANCE'
}
